import Admin from "@/components/Admin";
import AdminRoomCard from "@/components/admin/AdminRoomCard";
import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";

type Props = {};

const AdminRoom = (props: Props) => {
  const router = useRouter();
  const { adminroom } = router.query;

  console.log(router.query);

  return (
    <Admin>
      <>
        <Head>
          <title>Waiting in Queue</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="font-primary dot-texture h-[calc(100vh-60px)] w-full">
          <div className="w-full h-full flex justify-center items-center">
            <AdminRoomCard
              roomId={
                typeof adminroom == "string" || typeof adminroom == "undefined"
                  ? adminroom
                  : adminroom[0]
              }
            />
          </div>
        </main>
      </>
    </Admin>
  );
};

export default AdminRoom;
