import React from "react";
import Admin from "@/components/Admin";
import Head from "next/head";
import AdminView from "@/components/admin/AdminView";
import { UserAuth } from "@/lib/context/AuthContext";

type Props = {};

const AdminPage = (props: Props) => {
  const { user } = UserAuth();

  return (
    <Admin>
      <>
        <Head>
          <title>{user?.displayName}&apos;s Dashboard</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="font-primary dot-texture h-[calc(100vh-60px)] w-full">
          <div className="w-full h-full flex justify-center items-center">
            <AdminView />
          </div>
        </main>
      </>
    </Admin>
  );
};

export default AdminPage;
