import Head from "next/head";
import HomeCard from "@/components/homeCard/HomeCard";
import SigninCard from "@/components/SigninCard";
import { UserAuth } from "@/lib/context/AuthContext";
import { useEffect } from "react";
import { db } from "@/lib/utils/firebase";

export default function Home() {
  const { user } = UserAuth();

  useEffect(() => {
    // if user is already in queue, place them there
  }, []);

  return (
    <>
      <Head>
        <title>ICS Queue</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="font-primary dot-texture h-[calc(100vh-60px)] w-full">
        {/* Body container */}
        <div className="w-full h-full flex justify-center items-center">
          {user?.displayName ? <HomeCard /> : <SigninCard />}
        </div>
      </main>
    </>
  );
}
